# Generated by Django 2.1.4 on 2019-03-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='User',
        ),
        migrations.AddField(
            model_name='stocks',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stocks',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_val',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='stock_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='minQuantity',
            field=models.FloatField(default=0.0, help_text='Enter Stock Min Quantity'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='quantity',
            field=models.FloatField(default=0.0, help_text='Enter Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='unitCost',
            field=models.FloatField(default=0.0, help_text='Enter Stock Unit Cost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(help_text='Enter User Description'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
