# Generated by Django 2.1.4 on 2019-03-02 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190302_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Stocks'),
            preserve_default=False,
        ),
    ]
