# Generated by Django 2.1.4 on 2019-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190302_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', help_text='Enter User Name', max_length=200),
        ),
    ]
