# Generated by Django 2.1.4 on 2019-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='close',
            field=models.FloatField(default=0.0),
        ),
    ]
