# Generated by Django 2.1.4 on 2019-03-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_stocks_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='minQuantity',
        ),
    ]
