# Generated by Django 2.1.4 on 2019-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190303_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
