# Generated by Django 2.1.7 on 2019-03-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190303_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='symb',
            field=models.CharField(default='null', help_text='Enter Symbol', max_length=5),
            preserve_default=False,
        ),
    ]
